# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('restro_name', models.CharField(max_length=500, null=True)),
                ('cuisines', models.CharField(max_length=500, null=True)),
                ('avg_cost_for_two', models.IntegerField()),
                ('currency', models.CharField(max_length=500, null=True)),
                ('has_table_booking', models.CharField(max_length=500, null=True)),
                ('has_online_delivery', models.CharField(max_length=500, null=True)),
                ('rating', models.FloatField(default=0)),
                ('rating_color', models.CharField(max_length=500, null=True)),
                ('rating_text', models.CharField(max_length=500, null=True)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_restaurant_info',
            },
        ),
        migrations.CreateModel(
            name='RestaurantExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField()),
                ('city', models.CharField(max_length=500, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('locality', models.CharField(max_length=500, null=True)),
                ('locality_verbose', models.CharField(max_length=500, null=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('restro', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, related_name='restro_extra_map_restro_id', to='foodiedotcom.Restaurant')),
            ],
            options={
                'db_table': 'tbl_restaurant_extra_info',
            },
        ),
    ]
