# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-06 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(db_column='blog_id', primary_key=True, serialize=False)),
                ('blog', models.TextField(blank=True)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('views', models.IntegerField()),
                ('liked_by', models.TextField(blank=True)),
                ('disliked_by', models.TextField(blank=True)),
                ('commented_by', models.TextField(blank=True)),
                ('viewed_by', models.TextField(blank=True)),
                ('creationtime', models.DateTimeField()),
                ('isdeleted', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'tblblog',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('lastupdatetime', models.DateTimeField(auto_now=True)),
                ('creationtime', models.DateTimeField()),
                ('isdeleted', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'tblusers',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, related_name='blog_user_mapping', to='blogger_app.Users'),
        ),
    ]
