# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger_app', '0004_auto_20191206_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
