# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger_app', '0005_auto_20191206_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creationtime',
            field=models.IntegerField(default=0),
        ),
    ]
